# # values.yaml for Traefik with ClusterIP and proper port schema
ports:
  web:
    port: 80
    expose:
      enabled: true
    exposedPort: 80
    protocol: TCP

  websecure:
    port: 443
    expose:
      enabled: true
    exposedPort: 443
    protocol: TCP

  traefik:
    port: 8080
    expose:
      enabled: true
    exposedPort: 8080
    protocol: TCP

service:
  type: ClusterIP

api:
  dashboard: true
  insecure: false

accessLog:
  enabled: true

metrics:
  prometheus:
    enabled: true
